### ISSUE TITLE
AFP Split based on keyword or TLE

### ISSUE THREAD

**Issue by timyounes** [audreyt/openafp-utils#3]
Hi,

It is possible to split AFP file based on keyword or TLE values using this library?

Thanks in advance

**Comment by audreyt** [comment]
Yes. The `afp-split-scb.hs` files provides a sketch.

**Comment by timyounes** [comment]
Thank @audreyt 👍

**Comment by timyounes** [comment]
It can split AFP file using keyword?

**Comment by timyounes** [comment]
Hi @audreyt,

How can I run afp-split-scb.exe in Windows XP? The dialog appeared that the program was unable to locate msvcrt.dll in the system32 directory but the said dll is exist.

**Comment by audreyt** [comment]
It may be needed to re-install GHC 7 on Windows XP (using the 2015 version of https://www.haskell.org/platform/prior.html here) and recompile with `cabal install OpenAFP-Utils`

**Comment by timyounes** [comment]
Thanks @audreyt 👍  I will try it

**Comment by timyounes** [comment]
Hi @audreyt,

I try to run haskell in windows xp but it say that **unable to load package time-1.5.0.1**
