### ISSUE TITLE
Merging AFP File

### ISSUE THREAD

**Issue by timyounes** [audreyt/openafp-utils#4]
Hi,

Is this library capable of merging multiple AFP files?

Thanks in advance

**Comment by audreyt** [comment]
AFP files are designed so they can be concatenated. http://lists.topica.com/lists/afp-l/read/message.html?sort=a&mid=1720994119

**Comment by timyounes** [comment]
So this library did not support merging of AFP Files?

**Comment by audreyt** [comment]
Perhaps it can, but none of the existing scripts do this, so some experimentation would be needed.

**Comment by timyounes** [comment]
Thanks @audreyt 👍
